'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ActionLog
    Public Property ActionLogId As Integer
    Public Property EntityTypeId As Integer
    Public Property EntityId As Integer
    Public Property ActionTypeId As Byte
    Public Property UserId As Integer
    Public Property ActionDate As Date
    Public Property Description As String

    Public Overridable Property User As User

End Class
