'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class File
    Public Property FileId As Integer
    Public Property Guid As String
    Public Property Name As String
    Public Property Size As Nullable(Of Long)
    Public Property CreateDate As Date
    Public Property CreateById As Integer

    Public Overridable Property ProjectFiles As ICollection(Of ProjectFile) = New HashSet(Of ProjectFile)
    Public Overridable Property Users As ICollection(Of User) = New HashSet(Of User)
    Public Overridable Property UserStoryFiles As ICollection(Of UserStoryFile) = New HashSet(Of UserStoryFile)
    Public Overridable Property TaskFiles As ICollection(Of TaskFile) = New HashSet(Of TaskFile)

End Class
