'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class iWorkContext
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=iWorkContext")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ActionLogs() As DbSet(Of ActionLog)
    Public Overridable Property ProjectFiles() As DbSet(Of ProjectFile)
    Public Overridable Property ProjectMembers() As DbSet(Of ProjectMember)
    Public Overridable Property Projects() As DbSet(Of Project)
    Public Overridable Property ProjectWorkflows() As DbSet(Of ProjectWorkflow)
    Public Overridable Property Sprints() As DbSet(Of Sprint)
    Public Overridable Property TaskMembers() As DbSet(Of TaskMember)
    Public Overridable Property UserStories() As DbSet(Of UserStory)
    Public Overridable Property UserStoryFiles() As DbSet(Of UserStoryFile)
    Public Overridable Property Activities() As DbSet(Of Activity)
    Public Overridable Property Files() As DbSet(Of File)
    Public Overridable Property Users() As DbSet(Of User)
    Public Overridable Property TaskFiles() As DbSet(Of TaskFile)
    Public Overridable Property Tasks() As DbSet(Of Task)

End Class
