'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Project
    Public Property ProjectId As Integer
    Public Property Title As String
    Public Property Description As String
    Public Property Customer As String
    Public Property Url As String
    Public Property CodeName As String
    Public Property EstmatedHours As Integer
    Public Property Score As Integer
    Public Property StartDate As Date
    Public Property EndDate As Date
    Public Property Status As Byte
    Public Property Style As String

    Public Overridable Property ProjectFiles As ICollection(Of ProjectFile) = New HashSet(Of ProjectFile)
    Public Overridable Property ProjectMembers As ICollection(Of ProjectMember) = New HashSet(Of ProjectMember)
    Public Overridable Property ProjectWorkflows As ICollection(Of ProjectWorkflow) = New HashSet(Of ProjectWorkflow)
    Public Overridable Property Sprints As ICollection(Of Sprint) = New HashSet(Of Sprint)
    Public Overridable Property UserStories As ICollection(Of UserStory) = New HashSet(Of UserStory)
    Public Overridable Property Tasks As ICollection(Of Task) = New HashSet(Of Task)

End Class
