'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectWorkflow
    Public Property WorkflowId As Integer
    Public Property ProjectId As Integer
    Public Property Title As String
    Public Property ViewOrder As Byte

    Public Overridable Property Project As Project

End Class
