'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sprint
    Public Property SprintId As Integer
    Public Property ProjectId As Integer
    Public Property Title As String
    Public Property Description As String
    Public Property StartDate As Date
    Public Property EndDate As Date
    Public Property Status As Byte

    Public Overridable Property Project As Project
    Public Overridable Property UserStories As ICollection(Of UserStory) = New HashSet(Of UserStory)

End Class
