'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Task
    Public Property TaskId As Integer
    Public Property Title As String
    Public Property Description As String
    Public Property UserStoryId As Nullable(Of Integer)
    Public Property ProjectId As Integer
    Public Property Status As Byte
    Public Property DueDate As Date
    Public Property EstimatedDuartion As Integer
    Public Property Priority As Byte
    Public Property Score As Byte
    Public Property Archived As Boolean
    Public Property RealEndDate As Nullable(Of Date)

    Public Overridable Property Activities As ICollection(Of Activity) = New HashSet(Of Activity)
    Public Overridable Property Project As Project
    Public Overridable Property TaskFiles As ICollection(Of TaskFile) = New HashSet(Of TaskFile)
    Public Overridable Property TaskMembers As ICollection(Of TaskMember) = New HashSet(Of TaskMember)
    Public Overridable Property UserStory As UserStory

End Class
