'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property Id As Integer
    Public Property DisplayName As String
    Public Property FullName As String
    Public Property PictureFileId As Nullable(Of Integer)
    Public Property Description As String
    Public Property Mobile As String
    Public Property Home As String
    Public Property SecondaryEmail As String
    Public Property Address As String
    Public Property Status As Short
    Public Property RecruitmentStartDate As Date
    Public Property RecruitmentEndDate As Nullable(Of Date)
    Public Property CreateDate As Date
    Public Property LastUpdateDate As Date
    Public Property Email As String
    Public Property EmailConfirmed As Boolean
    Public Property PasswordHash As String
    Public Property SecurityStamp As String
    Public Property PhoneNumber As String
    Public Property PhoneNumberConfirmed As Boolean
    Public Property TwoFactorEnabled As Boolean
    Public Property LockoutEndDateUtc As Nullable(Of Date)
    Public Property LockoutEnabled As Boolean
    Public Property AccessFailedCount As Integer
    Public Property UserName As String

    Public Overridable Property ActionLogs As ICollection(Of ActionLog) = New HashSet(Of ActionLog)
    Public Overridable Property File As File
    Public Overridable Property ProjectMembers As ICollection(Of ProjectMember) = New HashSet(Of ProjectMember)
    Public Overridable Property TaskMembers As ICollection(Of TaskMember) = New HashSet(Of TaskMember)

End Class
