'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserStory
    Public Property UserStoryId As Integer
    Public Property ProjectId As Integer
    Public Property SprintId As Nullable(Of Integer)
    Public Property Title As String
    Public Property Description As String
    Public Property Score As Integer
    Public Property Status As Byte

    Public Overridable Property Project As Project
    Public Overridable Property Sprint As Sprint
    Public Overridable Property UserStoryFiles As ICollection(Of UserStoryFile) = New HashSet(Of UserStoryFile)
    Public Overridable Property Tasks As ICollection(Of Task) = New HashSet(Of Task)

End Class
